[2023-06-23T22:24:24.208+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: running-buses-clean-files-dag.clean-gcp-files manual__2023-06-23T22:20:13.759773+00:00 [queued]>
[2023-06-23T22:24:24.216+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: running-buses-clean-files-dag.clean-gcp-files manual__2023-06-23T22:20:13.759773+00:00 [queued]>
[2023-06-23T22:24:24.217+0000] {taskinstance.py:1308} INFO - Starting attempt 6 of 6
[2023-06-23T22:24:24.226+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): clean-gcp-files> on 2023-06-23 22:20:13.759773+00:00
[2023-06-23T22:24:24.232+0000] {standard_task_runner.py:57} INFO - Started process 1252 to run task
[2023-06-23T22:24:24.236+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'running-buses-clean-files-dag', 'clean-gcp-files', 'manual__2023-06-23T22:20:13.759773+00:00', '--job-id', '540', '--raw', '--subdir', 'DAGS_FOLDER/running_buses_clean_files.py', '--cfg-path', '/tmp/tmpcdym9_kb']
[2023-06-23T22:24:24.247+0000] {standard_task_runner.py:85} INFO - Job 540: Subtask clean-gcp-files
[2023-06-23T22:24:24.294+0000] {task_command.py:410} INFO - Running <TaskInstance: running-buses-clean-files-dag.clean-gcp-files manual__2023-06-23T22:20:13.759773+00:00 [running]> on host 6bba1fead03c
[2023-06-23T22:24:24.354+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='running-buses-clean-files-dag' AIRFLOW_CTX_TASK_ID='clean-gcp-files' AIRFLOW_CTX_EXECUTION_DATE='2023-06-23T22:20:13.759773+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-23T22:20:13.759773+00:00'
[2023-06-23T22:24:24.357+0000] {process_utils.py:181} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv_hanbw5t --system-site-packages
[2023-06-23T22:24:24.358+0000] {process_utils.py:185} INFO - Output:
[2023-06-23T22:24:24.981+0000] {process_utils.py:189} INFO - created virtual environment CPython3.11.4.final.0-64 in 288ms
[2023-06-23T22:24:24.982+0000] {process_utils.py:189} INFO -   creator CPython3Posix(dest=/tmp/venv_hanbw5t, clear=False, no_vcs_ignore=False, global=True)
[2023-06-23T22:24:24.982+0000] {process_utils.py:189} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2023-06-23T22:24:24.985+0000] {process_utils.py:189} INFO -     added seed packages: pip==23.1.2, setuptools==67.8.0, wheel==0.40.0
[2023-06-23T22:24:24.986+0000] {process_utils.py:189} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-06-23T22:24:25.001+0000] {process_utils.py:181} INFO - Executing cmd: /tmp/venv_hanbw5t/bin/pip install -r /tmp/venv_hanbw5t/requirements.txt
[2023-06-23T22:24:25.003+0000] {process_utils.py:185} INFO - Output:
[2023-06-23T22:24:26.707+0000] {process_utils.py:189} INFO - Requirement already satisfied: google-cloud-storage in /home/***/.local/lib/python3.11/site-packages (from -r /tmp/venv_hanbw5t/requirements.txt (line 1)) (2.9.0)
[2023-06-23T22:24:26.713+0000] {process_utils.py:189} INFO - Requirement already satisfied: google-auth<3.0dev,>=1.25.0 in /home/***/.local/lib/python3.11/site-packages (from google-cloud-storage->-r /tmp/venv_hanbw5t/requirements.txt (line 1)) (2.20.0)
[2023-06-23T22:24:26.715+0000] {process_utils.py:189} INFO - Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /home/***/.local/lib/python3.11/site-packages (from google-cloud-storage->-r /tmp/venv_hanbw5t/requirements.txt (line 1)) (2.11.0)
[2023-06-23T22:24:26.716+0000] {process_utils.py:189} INFO - Requirement already satisfied: google-cloud-core<3.0dev,>=2.3.0 in /home/***/.local/lib/python3.11/site-packages (from google-cloud-storage->-r /tmp/venv_hanbw5t/requirements.txt (line 1)) (2.3.2)
[2023-06-23T22:24:26.716+0000] {process_utils.py:189} INFO - Requirement already satisfied: google-resumable-media>=2.3.2 in /home/***/.local/lib/python3.11/site-packages (from google-cloud-storage->-r /tmp/venv_hanbw5t/requirements.txt (line 1)) (2.5.0)
[2023-06-23T22:24:26.719+0000] {process_utils.py:189} INFO - Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /home/***/.local/lib/python3.11/site-packages (from google-cloud-storage->-r /tmp/venv_hanbw5t/requirements.txt (line 1)) (2.31.0)
[2023-06-23T22:24:26.726+0000] {process_utils.py:189} INFO - Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in /home/***/.local/lib/python3.11/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage->-r /tmp/venv_hanbw5t/requirements.txt (line 1)) (1.59.1)
[2023-06-23T22:24:26.728+0000] {process_utils.py:189} INFO - Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5 in /home/***/.local/lib/python3.11/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage->-r /tmp/venv_hanbw5t/requirements.txt (line 1)) (4.23.2)
[2023-06-23T22:24:26.734+0000] {process_utils.py:189} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.11/site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venv_hanbw5t/requirements.txt (line 1)) (5.3.1)
[2023-06-23T22:24:26.736+0000] {process_utils.py:189} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.11/site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venv_hanbw5t/requirements.txt (line 1)) (0.2.8)
[2023-06-23T22:24:26.737+0000] {process_utils.py:189} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.11/site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venv_hanbw5t/requirements.txt (line 1)) (4.9)
[2023-06-23T22:24:26.738+0000] {process_utils.py:189} INFO - Requirement already satisfied: six>=1.9.0 in /home/***/.local/lib/python3.11/site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venv_hanbw5t/requirements.txt (line 1)) (1.16.0)
[2023-06-23T22:24:26.739+0000] {process_utils.py:189} INFO - Requirement already satisfied: urllib3<2.0 in /home/***/.local/lib/python3.11/site-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venv_hanbw5t/requirements.txt (line 1)) (1.26.16)
[2023-06-23T22:24:26.749+0000] {process_utils.py:189} INFO - Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /home/***/.local/lib/python3.11/site-packages (from google-resumable-media>=2.3.2->google-cloud-storage->-r /tmp/venv_hanbw5t/requirements.txt (line 1)) (1.5.0)
[2023-06-23T22:24:26.757+0000] {process_utils.py:189} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.11/site-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage->-r /tmp/venv_hanbw5t/requirements.txt (line 1)) (3.1.0)
[2023-06-23T22:24:26.759+0000] {process_utils.py:189} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.11/site-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage->-r /tmp/venv_hanbw5t/requirements.txt (line 1)) (3.4)
[2023-06-23T22:24:26.761+0000] {process_utils.py:189} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.11/site-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage->-r /tmp/venv_hanbw5t/requirements.txt (line 1)) (2023.5.7)
[2023-06-23T22:24:26.804+0000] {process_utils.py:189} INFO - Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/***/.local/lib/python3.11/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venv_hanbw5t/requirements.txt (line 1)) (0.4.8)
[2023-06-23T22:24:28.778+0000] {process_utils.py:181} INFO - Executing cmd: /tmp/venv_hanbw5t/bin/python /tmp/venv_hanbw5t/script.py /tmp/venv_hanbw5t/script.in /tmp/venv_hanbw5t/script.out /tmp/venv_hanbw5t/string_args.txt
[2023-06-23T22:24:28.779+0000] {process_utils.py:185} INFO - Output:
[2023-06-23T22:24:31.807+0000] {process_utils.py:189} INFO - [[34m2023-06-23T22:24:31.804+0000[0m] {[34mbase.py:[0m73} INFO[0m - Using connection ID 'google_cloud_default' for task execution.[0m
[2023-06-23T22:24:32.273+0000] {process_utils.py:189} INFO - removing invalid file: running_buses/year=2023/month=06/day=22/hour=20/a.csv, blob size: 0
[2023-06-23T22:24:32.294+0000] {process_utils.py:189} INFO - Blob running_buses/year=2023/month=06/day=22/hour=20/a.csv deleted.
[2023-06-23T22:24:32.580+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-06-23T22:24:32.595+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=running-buses-clean-files-dag, task_id=clean-gcp-files, execution_date=20230623T222013, start_date=20230623T222424, end_date=20230623T222432
[2023-06-23T22:24:32.658+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-23T22:24:32.683+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
