[2023-06-23T22:20:15.335+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: running-buses-clean-files-dag.clean-gcp-files manual__2023-06-23T22:20:13.759773+00:00 [queued]>
[2023-06-23T22:20:15.341+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: running-buses-clean-files-dag.clean-gcp-files manual__2023-06-23T22:20:13.759773+00:00 [queued]>
[2023-06-23T22:20:15.342+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-23T22:20:15.351+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): clean-gcp-files> on 2023-06-23 22:20:13.759773+00:00
[2023-06-23T22:20:15.356+0000] {standard_task_runner.py:57} INFO - Started process 1126 to run task
[2023-06-23T22:20:15.361+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'running-buses-clean-files-dag', 'clean-gcp-files', 'manual__2023-06-23T22:20:13.759773+00:00', '--job-id', '535', '--raw', '--subdir', 'DAGS_FOLDER/running_buses_clean_files.py', '--cfg-path', '/tmp/tmp2qair1r3']
[2023-06-23T22:20:15.364+0000] {standard_task_runner.py:85} INFO - Job 535: Subtask clean-gcp-files
[2023-06-23T22:20:15.406+0000] {task_command.py:410} INFO - Running <TaskInstance: running-buses-clean-files-dag.clean-gcp-files manual__2023-06-23T22:20:13.759773+00:00 [running]> on host 6bba1fead03c
[2023-06-23T22:20:15.464+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='running-buses-clean-files-dag' AIRFLOW_CTX_TASK_ID='clean-gcp-files' AIRFLOW_CTX_EXECUTION_DATE='2023-06-23T22:20:13.759773+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-23T22:20:13.759773+00:00'
[2023-06-23T22:20:15.467+0000] {process_utils.py:181} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvo0fwbgjx
[2023-06-23T22:20:15.468+0000] {process_utils.py:185} INFO - Output:
[2023-06-23T22:20:16.061+0000] {process_utils.py:189} INFO - created virtual environment CPython3.11.4.final.0-64 in 248ms
[2023-06-23T22:20:16.062+0000] {process_utils.py:189} INFO -   creator CPython3Posix(dest=/tmp/venvo0fwbgjx, clear=False, no_vcs_ignore=False, global=False)
[2023-06-23T22:20:16.063+0000] {process_utils.py:189} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2023-06-23T22:20:16.063+0000] {process_utils.py:189} INFO -     added seed packages: pip==23.1.2, setuptools==67.8.0, wheel==0.40.0
[2023-06-23T22:20:16.064+0000] {process_utils.py:189} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-06-23T22:20:16.078+0000] {process_utils.py:181} INFO - Executing cmd: /tmp/venvo0fwbgjx/bin/pip install -r /tmp/venvo0fwbgjx/requirements.txt
[2023-06-23T22:20:16.080+0000] {process_utils.py:185} INFO - Output:
[2023-06-23T22:20:18.010+0000] {process_utils.py:189} INFO - Collecting google-cloud-storage (from -r /tmp/venvo0fwbgjx/requirements.txt (line 1))
[2023-06-23T22:20:18.024+0000] {process_utils.py:189} INFO -   Using cached google_cloud_storage-2.9.0-py2.py3-none-any.whl (113 kB)
[2023-06-23T22:20:18.104+0000] {process_utils.py:189} INFO - Collecting google-auth<3.0dev,>=1.25.0 (from google-cloud-storage->-r /tmp/venvo0fwbgjx/requirements.txt (line 1))
[2023-06-23T22:20:18.107+0000] {process_utils.py:189} INFO -   Using cached google_auth-2.20.0-py2.py3-none-any.whl (181 kB)
[2023-06-23T22:20:18.181+0000] {process_utils.py:189} INFO - Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 (from google-cloud-storage->-r /tmp/venvo0fwbgjx/requirements.txt (line 1))
[2023-06-23T22:20:18.191+0000] {process_utils.py:189} INFO -   Using cached google_api_core-2.11.1-py3-none-any.whl (120 kB)
[2023-06-23T22:20:18.288+0000] {process_utils.py:189} INFO - Collecting google-cloud-core<3.0dev,>=2.3.0 (from google-cloud-storage->-r /tmp/venvo0fwbgjx/requirements.txt (line 1))
[2023-06-23T22:20:18.293+0000] {process_utils.py:189} INFO -   Using cached google_cloud_core-2.3.2-py2.py3-none-any.whl (29 kB)
[2023-06-23T22:20:18.342+0000] {process_utils.py:189} INFO - Collecting google-resumable-media>=2.3.2 (from google-cloud-storage->-r /tmp/venvo0fwbgjx/requirements.txt (line 1))
[2023-06-23T22:20:18.347+0000] {process_utils.py:189} INFO -   Using cached google_resumable_media-2.5.0-py2.py3-none-any.whl (77 kB)
[2023-06-23T22:20:18.405+0000] {process_utils.py:189} INFO - Collecting requests<3.0.0dev,>=2.18.0 (from google-cloud-storage->-r /tmp/venvo0fwbgjx/requirements.txt (line 1))
[2023-06-23T22:20:18.409+0000] {process_utils.py:189} INFO -   Using cached requests-2.31.0-py3-none-any.whl (62 kB)
[2023-06-23T22:20:18.459+0000] {process_utils.py:189} INFO - Collecting googleapis-common-protos<2.0.dev0,>=1.56.2 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage->-r /tmp/venvo0fwbgjx/requirements.txt (line 1))
[2023-06-23T22:20:18.464+0000] {process_utils.py:189} INFO -   Using cached googleapis_common_protos-1.59.1-py2.py3-none-any.whl (224 kB)
[2023-06-23T22:20:18.701+0000] {process_utils.py:189} INFO - Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage->-r /tmp/venvo0fwbgjx/requirements.txt (line 1))
[2023-06-23T22:20:18.712+0000] {process_utils.py:189} INFO -   Using cached protobuf-4.23.3-cp37-abi3-manylinux2014_aarch64.whl (303 kB)
[2023-06-23T22:20:18.766+0000] {process_utils.py:189} INFO - Collecting cachetools<6.0,>=2.0.0 (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venvo0fwbgjx/requirements.txt (line 1))
[2023-06-23T22:20:18.772+0000] {process_utils.py:189} INFO -   Using cached cachetools-5.3.1-py3-none-any.whl (9.3 kB)
[2023-06-23T22:20:18.805+0000] {process_utils.py:189} INFO - Collecting pyasn1-modules>=0.2.1 (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venvo0fwbgjx/requirements.txt (line 1))
[2023-06-23T22:20:18.809+0000] {process_utils.py:189} INFO -   Using cached pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)
[2023-06-23T22:20:18.847+0000] {process_utils.py:189} INFO - Collecting rsa<5,>=3.1.4 (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venvo0fwbgjx/requirements.txt (line 1))
[2023-06-23T22:20:18.850+0000] {process_utils.py:189} INFO -   Using cached rsa-4.9-py3-none-any.whl (34 kB)
[2023-06-23T22:20:18.879+0000] {process_utils.py:189} INFO - Collecting six>=1.9.0 (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venvo0fwbgjx/requirements.txt (line 1))
[2023-06-23T22:20:18.880+0000] {process_utils.py:189} INFO -   Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
[2023-06-23T22:20:18.916+0000] {process_utils.py:189} INFO - Collecting urllib3<2.0 (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venvo0fwbgjx/requirements.txt (line 1))
[2023-06-23T22:20:18.919+0000] {process_utils.py:189} INFO -   Using cached urllib3-1.26.16-py2.py3-none-any.whl (143 kB)
[2023-06-23T22:20:18.976+0000] {process_utils.py:189} INFO - Collecting google-crc32c<2.0dev,>=1.0 (from google-resumable-media>=2.3.2->google-cloud-storage->-r /tmp/venvo0fwbgjx/requirements.txt (line 1))
[2023-06-23T22:20:18.979+0000] {process_utils.py:189} INFO -   Using cached google_crc32c-1.5.0-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (32 kB)
[2023-06-23T22:20:19.029+0000] {process_utils.py:189} INFO - Collecting charset-normalizer<4,>=2 (from requests<3.0.0dev,>=2.18.0->google-cloud-storage->-r /tmp/venvo0fwbgjx/requirements.txt (line 1))
[2023-06-23T22:20:19.032+0000] {process_utils.py:189} INFO -   Using cached charset_normalizer-3.1.0-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (193 kB)
[2023-06-23T22:20:19.051+0000] {process_utils.py:189} INFO - Collecting idna<4,>=2.5 (from requests<3.0.0dev,>=2.18.0->google-cloud-storage->-r /tmp/venvo0fwbgjx/requirements.txt (line 1))
[2023-06-23T22:20:19.054+0000] {process_utils.py:189} INFO -   Using cached idna-3.4-py3-none-any.whl (61 kB)
[2023-06-23T22:20:19.089+0000] {process_utils.py:189} INFO - Collecting certifi>=2017.4.17 (from requests<3.0.0dev,>=2.18.0->google-cloud-storage->-r /tmp/venvo0fwbgjx/requirements.txt (line 1))
[2023-06-23T22:20:19.093+0000] {process_utils.py:189} INFO -   Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
[2023-06-23T22:20:19.157+0000] {process_utils.py:189} INFO - Collecting pyasn1<0.6.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venvo0fwbgjx/requirements.txt (line 1))
[2023-06-23T22:20:19.159+0000] {process_utils.py:189} INFO -   Using cached pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)
[2023-06-23T22:20:19.259+0000] {process_utils.py:189} INFO - Installing collected packages: urllib3, six, pyasn1, protobuf, idna, google-crc32c, charset-normalizer, certifi, cachetools, rsa, requests, pyasn1-modules, googleapis-common-protos, google-resumable-media, google-auth, google-api-core, google-cloud-core, google-cloud-storage
[2023-06-23T22:20:19.812+0000] {process_utils.py:189} INFO - Successfully installed cachetools-5.3.1 certifi-2023.5.7 charset-normalizer-3.1.0 google-api-core-2.11.1 google-auth-2.20.0 google-cloud-core-2.3.2 google-cloud-storage-2.9.0 google-crc32c-1.5.0 google-resumable-media-2.5.0 googleapis-common-protos-1.59.1 idna-3.4 protobuf-4.23.3 pyasn1-0.5.0 pyasn1-modules-0.3.0 requests-2.31.0 rsa-4.9 six-1.16.0 urllib3-1.26.16
[2023-06-23T22:20:20.021+0000] {process_utils.py:181} INFO - Executing cmd: /tmp/venvo0fwbgjx/bin/python /tmp/venvo0fwbgjx/script.py /tmp/venvo0fwbgjx/script.in /tmp/venvo0fwbgjx/script.out /tmp/venvo0fwbgjx/string_args.txt
[2023-06-23T22:20:20.024+0000] {process_utils.py:185} INFO - Output:
[2023-06-23T22:20:20.487+0000] {process_utils.py:189} INFO - Traceback (most recent call last):
[2023-06-23T22:20:20.488+0000] {process_utils.py:189} INFO -   File "/tmp/venvo0fwbgjx/script.py", line 44, in <module>
[2023-06-23T22:20:20.489+0000] {process_utils.py:189} INFO -     res = clean_files(*arg_dict["args"], **arg_dict["kwargs"])
[2023-06-23T22:20:20.490+0000] {process_utils.py:189} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-06-23T22:20:20.490+0000] {process_utils.py:189} INFO -   File "/tmp/venvo0fwbgjx/script.py", line 27, in clean_files
[2023-06-23T22:20:20.491+0000] {process_utils.py:189} INFO -     conn = BaseHook.get_connection('google_cloud_default')
[2023-06-23T22:20:20.492+0000] {process_utils.py:189} INFO -            ^^^^^^^^
[2023-06-23T22:20:20.493+0000] {process_utils.py:189} INFO - NameError: name 'BaseHook' is not defined
[2023-06-23T22:20:20.565+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 374, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 578, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path, tmp_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 428, in _execute_python_callable_in_subprocess
    execute_in_subprocess(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/process_utils.py", line 170, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/process_utils.py", line 193, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venvo0fwbgjx/bin/python', '/tmp/venvo0fwbgjx/script.py', '/tmp/venvo0fwbgjx/script.in', '/tmp/venvo0fwbgjx/script.out', '/tmp/venvo0fwbgjx/string_args.txt']' returned non-zero exit status 1.
[2023-06-23T22:20:20.585+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=running-buses-clean-files-dag, task_id=clean-gcp-files, execution_date=20230623T222013, start_date=20230623T222015, end_date=20230623T222020
[2023-06-23T22:20:20.596+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 535 for task clean-gcp-files (Command '['/tmp/venvo0fwbgjx/bin/python', '/tmp/venvo0fwbgjx/script.py', '/tmp/venvo0fwbgjx/script.in', '/tmp/venvo0fwbgjx/script.out', '/tmp/venvo0fwbgjx/string_args.txt']' returned non-zero exit status 1.; 1126)
[2023-06-23T22:20:20.635+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-23T22:20:20.652+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
