[2023-06-23T21:24:40.421+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: running-buses-clean-files-dag.clean-gcp-files manual__2023-06-23T21:24:39.356947+00:00 [queued]>
[2023-06-23T21:24:40.429+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: running-buses-clean-files-dag.clean-gcp-files manual__2023-06-23T21:24:39.356947+00:00 [queued]>
[2023-06-23T21:24:40.442+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-23T21:24:40.453+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): clean-gcp-files> on 2023-06-23 21:24:39.356947+00:00
[2023-06-23T21:24:40.460+0000] {standard_task_runner.py:57} INFO - Started process 262 to run task
[2023-06-23T21:24:40.464+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'running-buses-clean-files-dag', 'clean-gcp-files', 'manual__2023-06-23T21:24:39.356947+00:00', '--job-id', '517', '--raw', '--subdir', 'DAGS_FOLDER/running_buses_clean_files.py', '--cfg-path', '/tmp/tmp5zye25n1']
[2023-06-23T21:24:40.468+0000] {standard_task_runner.py:85} INFO - Job 517: Subtask clean-gcp-files
[2023-06-23T21:24:40.522+0000] {task_command.py:410} INFO - Running <TaskInstance: running-buses-clean-files-dag.clean-gcp-files manual__2023-06-23T21:24:39.356947+00:00 [running]> on host 6bba1fead03c
[2023-06-23T21:24:40.590+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='running-buses-clean-files-dag' AIRFLOW_CTX_TASK_ID='clean-gcp-files' AIRFLOW_CTX_EXECUTION_DATE='2023-06-23T21:24:39.356947+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-23T21:24:39.356947+00:00'
[2023-06-23T21:24:40.593+0000] {process_utils.py:181} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv8f2eogyg
[2023-06-23T21:24:40.594+0000] {process_utils.py:185} INFO - Output:
[2023-06-23T21:24:41.100+0000] {process_utils.py:189} INFO - created virtual environment CPython3.11.4.final.0-64 in 215ms
[2023-06-23T21:24:41.101+0000] {process_utils.py:189} INFO -   creator CPython3Posix(dest=/tmp/venv8f2eogyg, clear=False, no_vcs_ignore=False, global=False)
[2023-06-23T21:24:41.102+0000] {process_utils.py:189} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2023-06-23T21:24:41.103+0000] {process_utils.py:189} INFO -     added seed packages: pip==23.1.2, setuptools==67.7.2, wheel==0.40.0
[2023-06-23T21:24:41.104+0000] {process_utils.py:189} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-06-23T21:24:41.120+0000] {process_utils.py:181} INFO - Executing cmd: /tmp/venv8f2eogyg/bin/pip install -r /tmp/venv8f2eogyg/requirements.txt
[2023-06-23T21:24:41.122+0000] {process_utils.py:185} INFO - Output:
[2023-06-23T21:24:42.292+0000] {process_utils.py:189} INFO - Collecting google-cloud-storage (from -r /tmp/venv8f2eogyg/requirements.txt (line 1))
[2023-06-23T21:24:42.294+0000] {process_utils.py:189} INFO -   Using cached google_cloud_storage-2.9.0-py2.py3-none-any.whl (113 kB)
[2023-06-23T21:24:42.352+0000] {process_utils.py:189} INFO - Collecting google-auth<3.0dev,>=1.25.0 (from google-cloud-storage->-r /tmp/venv8f2eogyg/requirements.txt (line 1))
[2023-06-23T21:24:42.354+0000] {process_utils.py:189} INFO -   Using cached google_auth-2.20.0-py2.py3-none-any.whl (181 kB)
[2023-06-23T21:24:42.399+0000] {process_utils.py:189} INFO - Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 (from google-cloud-storage->-r /tmp/venv8f2eogyg/requirements.txt (line 1))
[2023-06-23T21:24:42.401+0000] {process_utils.py:189} INFO -   Using cached google_api_core-2.11.1-py3-none-any.whl (120 kB)
[2023-06-23T21:24:42.429+0000] {process_utils.py:189} INFO - Collecting google-cloud-core<3.0dev,>=2.3.0 (from google-cloud-storage->-r /tmp/venv8f2eogyg/requirements.txt (line 1))
[2023-06-23T21:24:42.430+0000] {process_utils.py:189} INFO -   Using cached google_cloud_core-2.3.2-py2.py3-none-any.whl (29 kB)
[2023-06-23T21:24:42.454+0000] {process_utils.py:189} INFO - Collecting google-resumable-media>=2.3.2 (from google-cloud-storage->-r /tmp/venv8f2eogyg/requirements.txt (line 1))
[2023-06-23T21:24:42.455+0000] {process_utils.py:189} INFO -   Using cached google_resumable_media-2.5.0-py2.py3-none-any.whl (77 kB)
[2023-06-23T21:24:42.489+0000] {process_utils.py:189} INFO - Collecting requests<3.0.0dev,>=2.18.0 (from google-cloud-storage->-r /tmp/venv8f2eogyg/requirements.txt (line 1))
[2023-06-23T21:24:42.490+0000] {process_utils.py:189} INFO -   Using cached requests-2.31.0-py3-none-any.whl (62 kB)
[2023-06-23T21:24:42.520+0000] {process_utils.py:189} INFO - Collecting googleapis-common-protos<2.0.dev0,>=1.56.2 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage->-r /tmp/venv8f2eogyg/requirements.txt (line 1))
[2023-06-23T21:24:42.521+0000] {process_utils.py:189} INFO -   Using cached googleapis_common_protos-1.59.1-py2.py3-none-any.whl (224 kB)
[2023-06-23T21:24:42.660+0000] {process_utils.py:189} INFO - Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage->-r /tmp/venv8f2eogyg/requirements.txt (line 1))
[2023-06-23T21:24:42.661+0000] {process_utils.py:189} INFO -   Using cached protobuf-4.23.3-cp37-abi3-manylinux2014_aarch64.whl (303 kB)
[2023-06-23T21:24:42.699+0000] {process_utils.py:189} INFO - Collecting cachetools<6.0,>=2.0.0 (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venv8f2eogyg/requirements.txt (line 1))
[2023-06-23T21:24:42.701+0000] {process_utils.py:189} INFO -   Using cached cachetools-5.3.1-py3-none-any.whl (9.3 kB)
[2023-06-23T21:24:42.728+0000] {process_utils.py:189} INFO - Collecting pyasn1-modules>=0.2.1 (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venv8f2eogyg/requirements.txt (line 1))
[2023-06-23T21:24:42.729+0000] {process_utils.py:189} INFO -   Using cached pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)
[2023-06-23T21:24:42.753+0000] {process_utils.py:189} INFO - Collecting rsa<5,>=3.1.4 (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venv8f2eogyg/requirements.txt (line 1))
[2023-06-23T21:24:42.754+0000] {process_utils.py:189} INFO -   Using cached rsa-4.9-py3-none-any.whl (34 kB)
[2023-06-23T21:24:42.774+0000] {process_utils.py:189} INFO - Collecting six>=1.9.0 (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venv8f2eogyg/requirements.txt (line 1))
[2023-06-23T21:24:42.775+0000] {process_utils.py:189} INFO -   Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
[2023-06-23T21:24:42.803+0000] {process_utils.py:189} INFO - Collecting urllib3<2.0 (from google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venv8f2eogyg/requirements.txt (line 1))
[2023-06-23T21:24:42.804+0000] {process_utils.py:189} INFO -   Using cached urllib3-1.26.16-py2.py3-none-any.whl (143 kB)
[2023-06-23T21:24:42.863+0000] {process_utils.py:189} INFO - Collecting google-crc32c<2.0dev,>=1.0 (from google-resumable-media>=2.3.2->google-cloud-storage->-r /tmp/venv8f2eogyg/requirements.txt (line 1))
[2023-06-23T21:24:42.865+0000] {process_utils.py:189} INFO -   Using cached google_crc32c-1.5.0-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (32 kB)
[2023-06-23T21:24:42.948+0000] {process_utils.py:189} INFO - Collecting charset-normalizer<4,>=2 (from requests<3.0.0dev,>=2.18.0->google-cloud-storage->-r /tmp/venv8f2eogyg/requirements.txt (line 1))
[2023-06-23T21:24:42.949+0000] {process_utils.py:189} INFO -   Using cached charset_normalizer-3.1.0-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (193 kB)
[2023-06-23T21:24:42.973+0000] {process_utils.py:189} INFO - Collecting idna<4,>=2.5 (from requests<3.0.0dev,>=2.18.0->google-cloud-storage->-r /tmp/venv8f2eogyg/requirements.txt (line 1))
[2023-06-23T21:24:42.982+0000] {process_utils.py:189} INFO -   Using cached idna-3.4-py3-none-any.whl (61 kB)
[2023-06-23T21:24:43.002+0000] {process_utils.py:189} INFO - Collecting certifi>=2017.4.17 (from requests<3.0.0dev,>=2.18.0->google-cloud-storage->-r /tmp/venv8f2eogyg/requirements.txt (line 1))
[2023-06-23T21:24:43.004+0000] {process_utils.py:189} INFO -   Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
[2023-06-23T21:24:43.045+0000] {process_utils.py:189} INFO - Collecting pyasn1<0.6.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=1.25.0->google-cloud-storage->-r /tmp/venv8f2eogyg/requirements.txt (line 1))
[2023-06-23T21:24:43.046+0000] {process_utils.py:189} INFO -   Using cached pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)
[2023-06-23T21:24:43.151+0000] {process_utils.py:189} INFO - Installing collected packages: urllib3, six, pyasn1, protobuf, idna, google-crc32c, charset-normalizer, certifi, cachetools, rsa, requests, pyasn1-modules, googleapis-common-protos, google-resumable-media, google-auth, google-api-core, google-cloud-core, google-cloud-storage
[2023-06-23T21:24:43.819+0000] {process_utils.py:189} INFO - Successfully installed cachetools-5.3.1 certifi-2023.5.7 charset-normalizer-3.1.0 google-api-core-2.11.1 google-auth-2.20.0 google-cloud-core-2.3.2 google-cloud-storage-2.9.0 google-crc32c-1.5.0 google-resumable-media-2.5.0 googleapis-common-protos-1.59.1 idna-3.4 protobuf-4.23.3 pyasn1-0.5.0 pyasn1-modules-0.3.0 requests-2.31.0 rsa-4.9 six-1.16.0 urllib3-1.26.16
[2023-06-23T21:24:44.035+0000] {process_utils.py:181} INFO - Executing cmd: /tmp/venv8f2eogyg/bin/python /tmp/venv8f2eogyg/script.py /tmp/venv8f2eogyg/script.in /tmp/venv8f2eogyg/script.out /tmp/venv8f2eogyg/string_args.txt
[2023-06-23T21:24:44.037+0000] {process_utils.py:185} INFO - Output:
[2023-06-23T21:24:47.452+0000] {process_utils.py:189} INFO - Traceback (most recent call last):
[2023-06-23T21:24:47.453+0000] {process_utils.py:189} INFO -   File "/tmp/venv8f2eogyg/script.py", line 43, in <module>
[2023-06-23T21:24:47.454+0000] {process_utils.py:189} INFO -     res = clean_files(*arg_dict["args"], **arg_dict["kwargs"])
[2023-06-23T21:24:47.455+0000] {process_utils.py:189} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-06-23T21:24:47.455+0000] {process_utils.py:189} INFO -   File "/tmp/venv8f2eogyg/script.py", line 33, in clean_files
[2023-06-23T21:24:47.457+0000] {process_utils.py:189} INFO -     storage_client = storage.Client(credentials='/opt/***/tmp_data/.google/bus-data-389717-3c31a20fe458.json')
[2023-06-23T21:24:47.457+0000] {process_utils.py:189} INFO -                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-06-23T21:24:47.458+0000] {process_utils.py:189} INFO -   File "/tmp/venv8f2eogyg/lib/python3.11/site-packages/google/cloud/storage/client.py", line 173, in __init__
[2023-06-23T21:24:47.459+0000] {process_utils.py:189} INFO -     super(Client, self).__init__(
[2023-06-23T21:24:47.460+0000] {process_utils.py:189} INFO -   File "/tmp/venv8f2eogyg/lib/python3.11/site-packages/google/cloud/client/__init__.py", line 320, in __init__
[2023-06-23T21:24:47.460+0000] {process_utils.py:189} INFO -     _ClientProjectMixin.__init__(self, project=project, credentials=credentials)
[2023-06-23T21:24:47.461+0000] {process_utils.py:189} INFO -   File "/tmp/venv8f2eogyg/lib/python3.11/site-packages/google/cloud/client/__init__.py", line 268, in __init__
[2023-06-23T21:24:47.462+0000] {process_utils.py:189} INFO -     project = self._determine_default(project)
[2023-06-23T21:24:47.463+0000] {process_utils.py:189} INFO -               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-06-23T21:24:47.463+0000] {process_utils.py:189} INFO -   File "/tmp/venv8f2eogyg/lib/python3.11/site-packages/google/cloud/client/__init__.py", line 287, in _determine_default
[2023-06-23T21:24:47.464+0000] {process_utils.py:189} INFO -     return _determine_default_project(project)
[2023-06-23T21:24:47.465+0000] {process_utils.py:189} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-06-23T21:24:47.466+0000] {process_utils.py:189} INFO -   File "/tmp/venv8f2eogyg/lib/python3.11/site-packages/google/cloud/_helpers/__init__.py", line 152, in _determine_default_project
[2023-06-23T21:24:47.467+0000] {process_utils.py:189} INFO -     _, project = google.auth.default()
[2023-06-23T21:24:47.468+0000] {process_utils.py:189} INFO -                  ^^^^^^^^^^^^^^^^^^^^^
[2023-06-23T21:24:47.469+0000] {process_utils.py:189} INFO -   File "/tmp/venv8f2eogyg/lib/python3.11/site-packages/google/auth/_default.py", line 692, in default
[2023-06-23T21:24:47.469+0000] {process_utils.py:189} INFO -     raise exceptions.DefaultCredentialsError(_CLOUD_SDK_MISSING_CREDENTIALS)
[2023-06-23T21:24:47.470+0000] {process_utils.py:189} INFO - google.auth.exceptions.DefaultCredentialsError: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[2023-06-23T21:24:47.531+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 374, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 578, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path, tmp_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 428, in _execute_python_callable_in_subprocess
    execute_in_subprocess(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/process_utils.py", line 170, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/process_utils.py", line 193, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/tmp/venv8f2eogyg/bin/python', '/tmp/venv8f2eogyg/script.py', '/tmp/venv8f2eogyg/script.in', '/tmp/venv8f2eogyg/script.out', '/tmp/venv8f2eogyg/string_args.txt']' returned non-zero exit status 1.
[2023-06-23T21:24:47.541+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=running-buses-clean-files-dag, task_id=clean-gcp-files, execution_date=20230623T212439, start_date=20230623T212440, end_date=20230623T212447
[2023-06-23T21:24:47.550+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 517 for task clean-gcp-files (Command '['/tmp/venv8f2eogyg/bin/python', '/tmp/venv8f2eogyg/script.py', '/tmp/venv8f2eogyg/script.in', '/tmp/venv8f2eogyg/script.out', '/tmp/venv8f2eogyg/string_args.txt']' returned non-zero exit status 1.; 262)
[2023-06-23T21:24:47.565+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-23T21:24:47.579+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
