[2023-06-14T00:04:16.587+0000] {processor.py:157} INFO - Started process (PID=1151) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:04:16.589+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:04:16.590+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:04:16.589+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:04:16.600+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:04:16.614+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.029 seconds
[2023-06-14T00:04:47.117+0000] {processor.py:157} INFO - Started process (PID=1208) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:04:47.119+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:04:47.120+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:04:47.120+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:04:47.125+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:04:47.138+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.024 seconds
[2023-06-14T00:05:17.900+0000] {processor.py:157} INFO - Started process (PID=1265) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:05:17.902+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:05:17.903+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:05:17.903+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:05:17.908+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:05:17.922+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.025 seconds
[2023-06-14T00:05:48.311+0000] {processor.py:157} INFO - Started process (PID=1322) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:05:48.314+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:05:48.314+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:05:48.314+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:05:48.318+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:05:48.333+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.024 seconds
[2023-06-14T00:06:18.716+0000] {processor.py:157} INFO - Started process (PID=1378) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:06:18.717+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:06:18.719+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:06:18.718+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:06:18.722+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:06:18.737+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.023 seconds
[2023-06-14T00:06:49.345+0000] {processor.py:157} INFO - Started process (PID=1434) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:06:49.347+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:06:49.348+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:06:49.348+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:06:49.351+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:06:49.365+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.022 seconds
[2023-06-14T00:07:19.899+0000] {processor.py:157} INFO - Started process (PID=1491) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:07:19.901+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:07:19.902+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:07:19.902+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:07:19.907+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:07:19.921+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.025 seconds
[2023-06-14T00:07:50.035+0000] {processor.py:157} INFO - Started process (PID=1548) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:07:50.036+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:07:50.037+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:07:50.037+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:07:50.042+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:07:50.056+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.024 seconds
[2023-06-14T00:08:20.705+0000] {processor.py:157} INFO - Started process (PID=1605) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:08:20.707+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:08:20.708+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:08:20.708+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:08:20.712+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:08:20.726+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.024 seconds
[2023-06-14T00:08:51.267+0000] {processor.py:157} INFO - Started process (PID=1663) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:08:51.269+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:08:51.270+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:08:51.270+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:08:51.273+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:08:51.287+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.022 seconds
[2023-06-14T00:09:21.706+0000] {processor.py:157} INFO - Started process (PID=1719) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:09:21.708+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:09:21.709+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:09:21.709+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:09:21.713+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:09:21.727+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.023 seconds
[2023-06-14T00:09:52.076+0000] {processor.py:157} INFO - Started process (PID=1776) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:09:52.078+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:09:52.079+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:09:52.079+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:09:52.083+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:09:52.097+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.024 seconds
[2023-06-14T00:10:22.371+0000] {processor.py:157} INFO - Started process (PID=1833) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:10:22.373+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:10:22.374+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:10:22.374+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:10:22.378+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:10:22.393+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.025 seconds
[2023-06-14T00:10:52.785+0000] {processor.py:157} INFO - Started process (PID=1890) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:10:52.787+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:10:52.788+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:10:52.788+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:10:52.792+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:10:52.806+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.024 seconds
[2023-06-14T00:11:23.120+0000] {processor.py:157} INFO - Started process (PID=1947) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:11:23.122+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:11:23.123+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:11:23.123+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:11:23.127+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:11:23.140+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.023 seconds
[2023-06-14T00:11:53.551+0000] {processor.py:157} INFO - Started process (PID=2004) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:11:53.552+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:11:53.553+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:11:53.553+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:11:53.557+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:11:53.579+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.031 seconds
[2023-06-14T00:12:23.944+0000] {processor.py:157} INFO - Started process (PID=2060) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:12:23.947+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:12:23.947+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:12:23.947+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:12:23.951+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:12:23.965+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.023 seconds
[2023-06-14T00:12:54.375+0000] {processor.py:157} INFO - Started process (PID=2117) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:12:54.377+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:12:54.378+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:12:54.378+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:12:54.382+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:12:54.396+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.024 seconds
[2023-06-14T00:13:24.749+0000] {processor.py:157} INFO - Started process (PID=2173) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:13:24.750+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:13:24.751+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:13:24.751+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:13:24.755+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:13:24.769+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.023 seconds
[2023-06-14T00:13:55.214+0000] {processor.py:157} INFO - Started process (PID=2230) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:13:55.215+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:13:55.216+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:13:55.216+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:13:55.220+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:13:55.234+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.023 seconds
[2023-06-14T00:14:25.766+0000] {processor.py:157} INFO - Started process (PID=2287) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:14:25.768+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:14:25.770+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:14:25.769+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:14:25.773+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:14:25.788+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.024 seconds
[2023-06-14T00:14:56.258+0000] {processor.py:157} INFO - Started process (PID=2344) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:14:56.260+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:14:56.261+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:14:56.261+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:14:56.265+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:14:56.282+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.028 seconds
[2023-06-14T00:15:26.788+0000] {processor.py:157} INFO - Started process (PID=2402) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:15:26.790+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:15:26.791+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:15:26.791+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:15:26.796+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:15:26.816+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.032 seconds
[2023-06-14T00:15:57.119+0000] {processor.py:157} INFO - Started process (PID=2459) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:15:57.121+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:15:57.123+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:15:57.122+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:15:57.127+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:15:57.143+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.027 seconds
[2023-06-14T00:16:27.428+0000] {processor.py:157} INFO - Started process (PID=2516) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:16:27.430+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:16:27.431+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:16:27.431+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:16:27.435+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:16:27.450+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.025 seconds
[2023-06-14T00:16:57.599+0000] {processor.py:157} INFO - Started process (PID=2573) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:16:57.601+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:16:57.601+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:16:57.601+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:16:57.605+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:16:57.622+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.026 seconds
[2023-06-14T00:17:28.251+0000] {processor.py:157} INFO - Started process (PID=2630) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:17:28.254+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:17:28.255+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:17:28.255+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:17:28.259+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:17:28.273+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.024 seconds
[2023-06-14T00:17:58.652+0000] {processor.py:157} INFO - Started process (PID=2687) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:17:58.653+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:17:58.654+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:17:58.654+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:17:58.658+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:17:58.672+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.023 seconds
[2023-06-14T00:18:29.098+0000] {processor.py:157} INFO - Started process (PID=2744) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:18:29.100+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:18:29.101+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:18:29.101+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:18:29.105+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:18:29.119+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.024 seconds
[2023-06-14T00:18:59.543+0000] {processor.py:157} INFO - Started process (PID=2802) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:18:59.544+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:18:59.545+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:18:59.545+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:18:59.549+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:18:59.563+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.023 seconds
[2023-06-14T00:19:29.931+0000] {processor.py:157} INFO - Started process (PID=2858) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:19:29.933+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:19:29.934+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:19:29.934+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:19:29.937+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:19:29.952+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.025 seconds
[2023-06-14T00:20:00.345+0000] {processor.py:157} INFO - Started process (PID=2915) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:20:00.347+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:20:00.348+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:20:00.348+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:20:00.352+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:20:00.366+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.025 seconds
[2023-06-14T00:20:30.817+0000] {processor.py:157} INFO - Started process (PID=2972) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:20:30.818+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:20:30.819+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:20:30.819+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:20:30.823+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:20:30.837+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.022 seconds
[2023-06-14T00:21:01.396+0000] {processor.py:157} INFO - Started process (PID=3029) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:21:01.398+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:21:01.399+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:21:01.399+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:21:01.403+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:21:01.418+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.025 seconds
[2023-06-14T00:21:31.459+0000] {processor.py:157} INFO - Started process (PID=3087) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:21:31.462+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:21:31.464+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:21:31.464+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:21:31.468+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:21:31.485+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.028 seconds
[2023-06-14T00:22:02.199+0000] {processor.py:157} INFO - Started process (PID=3145) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:22:02.201+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:22:02.202+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:22:02.202+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:22:02.206+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:22:02.220+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.024 seconds
[2023-06-14T00:22:08.732+0000] {processor.py:157} INFO - Started process (PID=3146) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:22:08.733+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:22:08.735+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:22:08.735+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:22:08.745+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:22:08.743+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 3, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:22:08.746+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:22:08.764+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.035 seconds
[2023-06-14T00:22:38.828+0000] {processor.py:157} INFO - Started process (PID=3203) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:22:38.830+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:22:38.832+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:22:38.832+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:22:38.837+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:22:38.836+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 3, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:22:38.838+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:22:38.860+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.035 seconds
[2023-06-14T00:23:09.077+0000] {processor.py:157} INFO - Started process (PID=3261) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:23:09.080+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:23:09.083+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:23:09.083+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:23:09.091+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:23:09.089+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 3, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:23:09.092+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:23:09.115+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.041 seconds
[2023-06-14T00:23:39.385+0000] {processor.py:157} INFO - Started process (PID=3318) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:23:39.387+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:23:39.389+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:23:39.389+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:23:39.395+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:23:39.393+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 3, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:23:39.396+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:23:39.414+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.033 seconds
[2023-06-14T00:23:57.870+0000] {processor.py:157} INFO - Started process (PID=3370) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:23:57.873+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:23:57.875+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:23:57.875+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:23:57.884+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:23:57.883+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 3, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:23:57.885+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:23:57.903+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.035 seconds
[2023-06-14T00:24:28.765+0000] {processor.py:157} INFO - Started process (PID=3427) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:24:28.767+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:24:28.770+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:24:28.770+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:24:28.774+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:24:28.773+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 3, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:24:28.775+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:24:28.795+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.034 seconds
[2023-06-14T00:24:51.565+0000] {processor.py:157} INFO - Started process (PID=3469) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:24:51.567+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:24:51.569+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:24:51.569+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:24:51.582+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:24:51.581+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 3, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:24:51.583+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:24:51.605+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.043 seconds
[2023-06-14T00:24:55.120+0000] {processor.py:157} INFO - Started process (PID=3480) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:24:55.121+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:24:55.123+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:24:55.123+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:24:55.133+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:24:55.132+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:24:55.134+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:24:55.151+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.034 seconds
[2023-06-14T00:25:25.750+0000] {processor.py:157} INFO - Started process (PID=3537) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:25:25.751+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:25:25.753+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:25:25.753+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:25:25.759+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:25:25.758+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:25:25.760+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:25:25.778+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.031 seconds
[2023-06-14T00:25:56.461+0000] {processor.py:157} INFO - Started process (PID=3594) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:25:56.464+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:25:56.466+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:25:56.466+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:25:56.473+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:25:56.471+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:25:56.474+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:25:56.493+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.034 seconds
[2023-06-14T00:26:27.206+0000] {processor.py:157} INFO - Started process (PID=3651) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:26:27.208+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:26:27.210+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:26:27.210+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:26:27.217+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:26:27.216+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:26:27.218+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:26:27.239+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.036 seconds
[2023-06-14T00:26:34.720+0000] {processor.py:157} INFO - Started process (PID=3662) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:26:34.722+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:26:34.725+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:26:34.725+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:26:34.739+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:26:34.737+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:26:34.742+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:26:34.766+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.050 seconds
[2023-06-14T00:27:04.969+0000] {processor.py:157} INFO - Started process (PID=3719) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:27:04.970+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:27:04.972+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:27:04.972+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:27:04.979+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:27:04.977+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:27:04.979+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:27:04.999+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.033 seconds
[2023-06-14T00:27:35.616+0000] {processor.py:157} INFO - Started process (PID=3776) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:27:35.618+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:27:35.620+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:27:35.620+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:27:35.626+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:27:35.625+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:27:35.627+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:27:35.645+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.032 seconds
[2023-06-14T00:28:06.222+0000] {processor.py:157} INFO - Started process (PID=3833) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:28:06.223+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:28:06.226+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:28:06.226+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:28:06.231+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:28:06.229+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:28:06.231+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:28:06.249+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.030 seconds
[2023-06-14T00:28:36.410+0000] {processor.py:157} INFO - Started process (PID=3890) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:28:36.412+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:28:36.414+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:28:36.414+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:28:36.419+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:28:36.418+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:28:36.421+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:28:36.439+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.031 seconds
[2023-06-14T00:29:06.698+0000] {processor.py:157} INFO - Started process (PID=3946) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:29:06.702+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:29:06.707+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:29:06.707+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:29:06.715+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:29:06.713+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:29:06.717+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:29:06.752+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.061 seconds
[2023-06-14T00:29:36.832+0000] {processor.py:157} INFO - Started process (PID=4003) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:29:36.834+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:29:36.836+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:29:36.836+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:29:36.841+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:29:36.840+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:29:36.842+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:29:36.860+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.031 seconds
[2023-06-14T00:30:06.940+0000] {processor.py:157} INFO - Started process (PID=4060) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:30:06.942+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:30:06.945+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:30:06.945+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:30:06.950+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:30:06.949+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:30:06.951+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:30:06.972+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.035 seconds
[2023-06-14T00:30:37.113+0000] {processor.py:157} INFO - Started process (PID=4117) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:30:37.114+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:30:37.116+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:30:37.116+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:30:37.121+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:30:37.120+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:30:37.122+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:30:37.141+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.031 seconds
[2023-06-14T00:31:07.832+0000] {processor.py:157} INFO - Started process (PID=4170) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:31:07.834+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:31:07.836+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:31:07.836+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:31:07.840+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:31:07.839+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:31:07.841+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:31:07.864+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.035 seconds
[2023-06-14T00:31:38.805+0000] {processor.py:157} INFO - Started process (PID=4227) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:31:38.807+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:31:38.809+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:31:38.809+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:31:38.815+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:31:38.813+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:31:38.816+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:31:38.841+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.040 seconds
[2023-06-14T00:32:09.671+0000] {processor.py:157} INFO - Started process (PID=4283) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:32:09.673+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:32:09.675+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:32:09.675+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:32:09.681+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:32:09.679+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:32:09.682+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:32:09.700+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.032 seconds
[2023-06-14T00:32:40.520+0000] {processor.py:157} INFO - Started process (PID=4340) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:32:40.522+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:32:40.525+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:32:40.524+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:32:40.529+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:32:40.528+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:32:40.530+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:32:40.549+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.034 seconds
[2023-06-14T00:33:11.107+0000] {processor.py:157} INFO - Started process (PID=4397) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:33:11.109+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:33:11.111+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:33:11.111+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:33:11.117+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:33:11.116+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:33:11.118+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:33:11.136+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.033 seconds
[2023-06-14T00:33:41.714+0000] {processor.py:157} INFO - Started process (PID=4454) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:33:41.716+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:33:41.719+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:33:41.719+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:33:41.723+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:33:41.722+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:33:41.724+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:33:41.742+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.031 seconds
[2023-06-14T00:34:12.346+0000] {processor.py:157} INFO - Started process (PID=4511) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:34:12.349+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:34:12.351+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:34:12.351+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:34:12.356+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:34:12.355+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:34:12.357+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:34:12.376+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.032 seconds
[2023-06-14T00:34:43.085+0000] {processor.py:157} INFO - Started process (PID=4568) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:34:43.087+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:34:43.089+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:34:43.089+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:34:43.094+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:34:43.092+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:34:43.095+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:34:43.112+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.031 seconds
[2023-06-14T00:35:13.801+0000] {processor.py:157} INFO - Started process (PID=4625) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:35:13.804+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:35:13.806+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:35:13.806+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:35:13.813+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:35:13.811+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:35:13.814+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:35:13.840+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.042 seconds
[2023-06-14T00:35:44.414+0000] {processor.py:157} INFO - Started process (PID=4681) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:35:44.417+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:35:44.421+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:35:44.421+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:35:44.428+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:35:44.426+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:35:44.429+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:35:44.477+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.068 seconds
[2023-06-14T00:36:14.553+0000] {processor.py:157} INFO - Started process (PID=4737) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:36:14.556+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:36:14.560+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:36:14.559+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:36:14.565+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:36:14.564+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:36:14.568+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:36:14.592+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.043 seconds
[2023-06-14T00:36:45.348+0000] {processor.py:157} INFO - Started process (PID=4800) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:36:45.349+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:36:45.352+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:36:45.352+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:36:45.358+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:36:45.356+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:36:45.359+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:36:45.378+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.033 seconds
[2023-06-14T00:37:15.455+0000] {processor.py:157} INFO - Started process (PID=4857) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:37:15.458+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:37:15.462+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:37:15.462+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:37:15.470+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:37:15.468+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:37:15.471+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:37:15.498+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.047 seconds
[2023-06-14T00:37:46.505+0000] {processor.py:157} INFO - Started process (PID=4913) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:37:46.508+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:37:46.511+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:37:46.511+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:37:46.516+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:37:46.515+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:37:46.517+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:37:46.535+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.032 seconds
[2023-06-14T00:38:16.713+0000] {processor.py:157} INFO - Started process (PID=4969) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:38:16.715+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:38:16.717+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:38:16.717+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:38:16.722+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:38:16.721+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:38:16.723+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:38:16.744+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.034 seconds
[2023-06-14T00:38:47.426+0000] {processor.py:157} INFO - Started process (PID=5020) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:38:47.427+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:38:47.430+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:38:47.430+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:38:47.435+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:38:47.433+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:38:47.436+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:38:47.454+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.031 seconds
[2023-06-14T00:39:18.066+0000] {processor.py:157} INFO - Started process (PID=5076) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:39:18.069+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:39:18.072+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:39:18.072+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:39:18.079+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:39:18.078+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:39:18.080+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:39:18.105+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.043 seconds
[2023-06-14T00:39:48.861+0000] {processor.py:157} INFO - Started process (PID=5133) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:39:48.863+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:39:48.866+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:39:48.866+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:39:48.872+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:39:48.871+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:39:48.873+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:39:48.895+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.038 seconds
[2023-06-14T00:40:19.660+0000] {processor.py:157} INFO - Started process (PID=5190) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:40:19.662+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:40:19.664+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:40:19.664+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:40:19.670+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:40:19.668+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:40:19.672+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:40:19.692+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.036 seconds
[2023-06-14T00:40:50.347+0000] {processor.py:157} INFO - Started process (PID=5247) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:40:50.349+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:40:50.353+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:40:50.353+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:40:50.358+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:40:50.357+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:40:50.359+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:40:50.378+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.035 seconds
[2023-06-14T00:41:21.154+0000] {processor.py:157} INFO - Started process (PID=5304) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:41:21.156+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:41:21.159+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:41:21.159+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:41:21.163+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:41:21.162+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:41:21.164+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:41:21.183+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.033 seconds
[2023-06-14T00:41:52.062+0000] {processor.py:157} INFO - Started process (PID=5361) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:41:52.064+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:41:52.067+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:41:52.067+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:41:52.072+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:41:52.071+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:41:52.073+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:41:52.091+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.033 seconds
[2023-06-14T00:42:22.891+0000] {processor.py:157} INFO - Started process (PID=5418) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:42:22.894+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:42:22.898+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:42:22.898+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:42:22.906+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:42:22.904+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:42:22.907+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:42:22.927+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.039 seconds
[2023-06-14T00:42:53.735+0000] {processor.py:157} INFO - Started process (PID=5475) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:42:53.736+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:42:53.739+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:42:53.739+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:42:53.744+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:42:53.742+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:42:53.744+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:42:53.767+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.035 seconds
[2023-06-14T00:43:23.874+0000] {processor.py:157} INFO - Started process (PID=5532) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:43:23.876+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:43:23.878+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:43:23.878+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:43:23.883+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:43:23.881+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:43:23.883+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:43:23.901+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.030 seconds
[2023-06-14T00:43:54.277+0000] {processor.py:157} INFO - Started process (PID=5589) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:43:54.279+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:43:54.281+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:43:54.281+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:43:54.286+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:43:54.285+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:43:54.287+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:43:54.306+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.032 seconds
[2023-06-14T00:44:24.884+0000] {processor.py:157} INFO - Started process (PID=5646) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:44:24.886+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:44:24.890+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:44:24.890+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:44:24.898+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:44:24.896+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:44:24.899+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:44:24.925+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.044 seconds
[2023-06-14T00:44:55.603+0000] {processor.py:157} INFO - Started process (PID=5703) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:44:55.605+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:44:55.607+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:44:55.607+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:44:55.613+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:44:55.612+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:44:55.614+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:44:55.631+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.030 seconds
[2023-06-14T00:45:26.187+0000] {processor.py:157} INFO - Started process (PID=5760) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:45:26.190+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:45:26.193+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:45:26.193+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:45:26.198+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:45:26.197+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:45:26.199+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:45:26.218+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.033 seconds
[2023-06-14T00:45:56.955+0000] {processor.py:157} INFO - Started process (PID=5817) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:45:56.956+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:45:56.958+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:45:56.958+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:45:56.963+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:45:56.962+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:45:56.964+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:45:56.982+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.029 seconds
[2023-06-14T00:46:27.451+0000] {processor.py:157} INFO - Started process (PID=5874) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:46:27.454+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:46:27.456+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:46:27.456+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:46:27.461+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:46:27.460+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:46:27.462+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:46:27.479+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.032 seconds
[2023-06-14T00:46:58.047+0000] {processor.py:157} INFO - Started process (PID=5931) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:46:58.050+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:46:58.053+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:46:58.053+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:46:58.060+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:46:58.058+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:46:58.061+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:46:58.083+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.040 seconds
[2023-06-14T00:47:28.315+0000] {processor.py:157} INFO - Started process (PID=5989) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:47:28.317+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:47:28.319+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:47:28.319+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:47:28.326+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:47:28.324+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:47:28.327+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:47:28.347+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.035 seconds
[2023-06-14T00:47:59.020+0000] {processor.py:157} INFO - Started process (PID=6046) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:47:59.022+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:47:59.025+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:47:59.025+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:47:59.030+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:47:59.029+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:47:59.031+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:47:59.050+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.033 seconds
[2023-06-14T00:48:29.570+0000] {processor.py:157} INFO - Started process (PID=6103) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:48:29.573+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:48:29.575+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:48:29.575+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:48:29.580+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:48:29.579+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:48:29.581+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:48:29.599+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.031 seconds
[2023-06-14T00:49:00.213+0000] {processor.py:157} INFO - Started process (PID=6160) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:49:00.216+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:49:00.218+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:49:00.218+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:49:00.223+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:49:00.222+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:49:00.224+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:49:00.242+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.033 seconds
[2023-06-14T00:49:30.875+0000] {processor.py:157} INFO - Started process (PID=6217) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:49:30.877+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:49:30.880+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:49:30.880+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:49:30.885+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:49:30.884+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:49:30.886+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:49:30.903+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.031 seconds
[2023-06-14T00:50:01.522+0000] {processor.py:157} INFO - Started process (PID=6274) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:50:01.524+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:50:01.526+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:50:01.526+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:50:01.532+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:50:01.531+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:50:01.533+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:50:01.551+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.031 seconds
[2023-06-14T00:50:32.138+0000] {processor.py:157} INFO - Started process (PID=6330) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:50:32.140+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:50:32.143+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:50:32.142+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:50:32.148+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:50:32.146+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:50:32.149+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:50:32.166+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.031 seconds
[2023-06-14T00:51:02.674+0000] {processor.py:157} INFO - Started process (PID=6387) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:51:02.676+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:51:02.679+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:51:02.679+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:51:02.685+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:51:02.683+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:51:02.686+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:51:02.705+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.034 seconds
[2023-06-14T00:51:33.347+0000] {processor.py:157} INFO - Started process (PID=6444) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:51:33.349+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:51:33.352+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:51:33.351+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:51:33.358+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:51:33.356+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:51:33.358+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:51:33.376+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.034 seconds
[2023-06-14T00:52:04.008+0000] {processor.py:157} INFO - Started process (PID=6501) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:52:04.010+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:52:04.012+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:52:04.012+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:52:04.017+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:52:04.016+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:52:04.018+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:52:04.038+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.033 seconds
[2023-06-14T00:52:34.687+0000] {processor.py:157} INFO - Started process (PID=6558) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:52:34.689+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:52:34.692+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:52:34.691+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:52:34.697+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:52:34.695+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:52:34.698+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:52:34.717+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.034 seconds
[2023-06-14T00:53:05.284+0000] {processor.py:157} INFO - Started process (PID=6615) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:53:05.285+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:53:05.287+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:53:05.287+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:53:05.292+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:53:05.291+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:53:05.293+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:53:05.310+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.028 seconds
[2023-06-14T00:53:36.029+0000] {processor.py:157} INFO - Started process (PID=6672) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:53:36.031+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:53:36.033+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:53:36.033+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:53:36.037+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:53:36.036+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:53:36.038+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:53:36.055+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.029 seconds
[2023-06-14T00:54:06.547+0000] {processor.py:157} INFO - Started process (PID=6730) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:54:06.549+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:54:06.553+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:54:06.553+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:54:06.560+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:54:06.557+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:54:06.561+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:54:06.589+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.046 seconds
[2023-06-14T00:54:37.483+0000] {processor.py:157} INFO - Started process (PID=6787) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:54:37.486+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:54:37.488+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:54:37.488+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:54:37.498+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:54:37.495+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:54:37.499+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:54:37.518+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.038 seconds
[2023-06-14T00:55:08.186+0000] {processor.py:157} INFO - Started process (PID=6844) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:55:08.188+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:55:08.193+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:55:08.193+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:55:08.201+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:55:08.199+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:55:08.202+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:55:08.235+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.054 seconds
[2023-06-14T00:55:38.828+0000] {processor.py:157} INFO - Started process (PID=6901) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:55:38.829+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:55:38.832+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:55:38.832+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:55:38.838+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:55:38.837+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:55:38.839+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:55:38.866+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.042 seconds
[2023-06-14T00:56:09.707+0000] {processor.py:157} INFO - Started process (PID=6958) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:56:09.709+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:56:09.712+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:56:09.712+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:56:09.718+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:56:09.716+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:56:09.719+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:56:09.740+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.036 seconds
[2023-06-14T00:56:40.116+0000] {processor.py:157} INFO - Started process (PID=7016) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:56:40.118+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:56:40.122+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:56:40.122+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:56:40.130+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:56:40.127+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:56:40.131+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:56:40.148+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.037 seconds
[2023-06-14T00:57:10.247+0000] {processor.py:157} INFO - Started process (PID=7073) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:57:10.249+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:57:10.251+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:57:10.251+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:57:10.256+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:57:10.255+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:57:10.257+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:57:10.277+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.033 seconds
[2023-06-14T00:57:40.393+0000] {processor.py:157} INFO - Started process (PID=7129) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:57:40.395+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:57:40.398+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:57:40.398+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:57:40.404+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:57:40.402+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:57:40.404+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:57:40.426+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.036 seconds
[2023-06-14T00:58:11.166+0000] {processor.py:157} INFO - Started process (PID=7186) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:58:11.169+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:58:11.171+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:58:11.171+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:58:11.177+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:58:11.175+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:58:11.178+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:58:11.197+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.033 seconds
[2023-06-14T00:58:41.646+0000] {processor.py:157} INFO - Started process (PID=7243) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:58:41.647+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:58:41.649+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:58:41.649+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:58:41.655+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:58:41.653+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:58:41.655+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:58:41.673+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.031 seconds
[2023-06-14T00:59:11.975+0000] {processor.py:157} INFO - Started process (PID=7300) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:59:11.977+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:59:11.979+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:59:11.979+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:59:11.985+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:59:11.983+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:59:11.986+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:59:12.003+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.032 seconds
[2023-06-14T00:59:42.499+0000] {processor.py:157} INFO - Started process (PID=7357) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T00:59:42.501+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T00:59:42.503+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:59:42.503+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:59:42.509+0000] {logging_mixin.py:149} INFO - [2023-06-14T00:59:42.507+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T00:59:42.511+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T00:59:42.532+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.035 seconds
[2023-06-14T01:00:12.649+0000] {processor.py:157} INFO - Started process (PID=7415) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:00:12.651+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:00:12.653+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:00:12.653+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:00:12.657+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:00:12.656+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:00:12.658+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:00:12.677+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.030 seconds
[2023-06-14T01:00:42.879+0000] {processor.py:157} INFO - Started process (PID=7472) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:00:42.881+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:00:42.884+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:00:42.884+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:00:42.890+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:00:42.889+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:00:42.891+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:00:42.912+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.035 seconds
[2023-06-14T01:01:13.545+0000] {processor.py:157} INFO - Started process (PID=7529) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:01:13.548+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:01:13.550+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:01:13.550+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:01:13.556+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:01:13.554+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:01:13.556+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:01:13.574+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.030 seconds
[2023-06-14T01:01:44.429+0000] {processor.py:157} INFO - Started process (PID=7586) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:01:44.431+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:01:44.433+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:01:44.433+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:01:44.439+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:01:44.437+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:01:44.440+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:01:44.459+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.033 seconds
[2023-06-14T01:02:14.669+0000] {processor.py:157} INFO - Started process (PID=7643) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:02:14.671+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:02:14.675+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:02:14.675+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:02:14.684+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:02:14.681+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:02:14.686+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:02:14.711+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.046 seconds
[2023-06-14T01:02:45.137+0000] {processor.py:157} INFO - Started process (PID=7700) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:02:45.138+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:02:45.141+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:02:45.141+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:02:45.146+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:02:45.145+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:02:45.147+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:02:45.165+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.030 seconds
[2023-06-14T01:03:15.433+0000] {processor.py:157} INFO - Started process (PID=7757) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:03:15.436+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:03:15.439+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:03:15.439+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:03:15.447+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:03:15.444+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:03:15.448+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:03:15.471+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.041 seconds
[2023-06-14T01:03:45.700+0000] {processor.py:157} INFO - Started process (PID=7814) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:03:45.702+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:03:45.703+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:03:45.703+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:03:45.710+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:03:45.708+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:03:45.711+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:03:45.729+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.032 seconds
[2023-06-14T01:04:16.425+0000] {processor.py:157} INFO - Started process (PID=7871) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:04:16.427+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:04:16.429+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:04:16.429+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:04:16.435+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:04:16.433+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:04:16.435+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:04:16.456+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.034 seconds
[2023-06-14T01:04:47.209+0000] {processor.py:157} INFO - Started process (PID=7928) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:04:47.212+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:04:47.214+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:04:47.214+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:04:47.219+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:04:47.218+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:04:47.220+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:04:47.239+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.032 seconds
[2023-06-14T01:05:17.742+0000] {processor.py:157} INFO - Started process (PID=7985) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:05:17.744+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:05:17.746+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:05:17.746+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:05:17.753+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:05:17.751+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:05:17.754+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:05:17.779+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.041 seconds
[2023-06-14T01:05:47.902+0000] {processor.py:157} INFO - Started process (PID=8041) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:05:47.904+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:05:47.907+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:05:47.907+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:05:47.913+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:05:47.911+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:05:47.914+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:05:47.935+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.036 seconds
[2023-06-14T01:06:18.044+0000] {processor.py:157} INFO - Started process (PID=8098) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:06:18.045+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:06:18.048+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:06:18.048+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:06:18.053+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:06:18.051+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:06:18.054+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:06:18.077+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.036 seconds
[2023-06-14T01:06:48.202+0000] {processor.py:157} INFO - Started process (PID=8156) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:06:48.204+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:06:48.206+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:06:48.206+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:06:48.212+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:06:48.210+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:06:48.213+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:06:48.234+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.035 seconds
[2023-06-14T01:07:18.414+0000] {processor.py:157} INFO - Started process (PID=8213) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:07:18.416+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:07:18.418+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:07:18.418+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:07:18.423+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:07:18.422+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:07:18.424+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:07:18.443+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.032 seconds
[2023-06-14T01:07:49.059+0000] {processor.py:157} INFO - Started process (PID=8278) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:07:49.062+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:07:49.064+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:07:49.064+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:07:49.069+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:07:49.068+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:07:49.071+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:07:49.089+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.032 seconds
[2023-06-14T01:08:19.683+0000] {processor.py:157} INFO - Started process (PID=8334) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:08:19.685+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:08:19.688+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:08:19.688+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:08:19.694+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:08:19.692+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:08:19.695+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:08:19.712+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.033 seconds
[2023-06-14T01:08:50.071+0000] {processor.py:157} INFO - Started process (PID=8391) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:08:50.073+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:08:50.076+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:08:50.076+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:08:50.081+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:08:50.080+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:08:50.082+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:08:50.100+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.033 seconds
[2023-06-14T01:09:20.766+0000] {processor.py:157} INFO - Started process (PID=8448) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:09:20.769+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:09:20.772+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:09:20.772+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:09:20.777+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:09:20.776+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:09:20.779+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:09:20.798+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.035 seconds
[2023-06-14T01:09:51.453+0000] {processor.py:157} INFO - Started process (PID=8506) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:09:51.456+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:09:51.462+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:09:51.461+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:09:51.471+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:09:51.469+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:09:51.472+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:09:51.498+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.050 seconds
[2023-06-14T01:10:21.630+0000] {processor.py:157} INFO - Started process (PID=8562) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:10:21.633+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:10:21.635+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:10:21.635+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:10:21.641+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:10:21.639+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:10:21.641+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:10:21.661+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.033 seconds
[2023-06-14T01:10:51.789+0000] {processor.py:157} INFO - Started process (PID=8619) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:10:51.791+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:10:51.794+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:10:51.794+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:10:51.800+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:10:51.798+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:10:51.801+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:10:51.820+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.034 seconds
[2023-06-14T01:11:22.213+0000] {processor.py:157} INFO - Started process (PID=8676) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:11:22.215+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:11:22.218+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:11:22.218+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:11:22.224+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:11:22.223+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:11:22.225+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:11:22.244+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.034 seconds
[2023-06-14T01:11:52.312+0000] {processor.py:157} INFO - Started process (PID=8733) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:11:52.314+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:11:52.319+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:11:52.318+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:11:52.323+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:11:52.322+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:11:52.324+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:11:52.344+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.034 seconds
[2023-06-14T01:12:22.528+0000] {processor.py:157} INFO - Started process (PID=8790) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:12:22.531+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:12:22.535+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:12:22.535+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:12:22.541+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:12:22.540+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:12:22.542+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:12:22.563+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.038 seconds
[2023-06-14T01:12:52.740+0000] {processor.py:157} INFO - Started process (PID=8847) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:12:52.742+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:12:52.745+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:12:52.745+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:12:52.752+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:12:52.750+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:12:52.752+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:12:52.775+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.039 seconds
[2023-06-14T01:13:22.833+0000] {processor.py:157} INFO - Started process (PID=8905) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:13:22.835+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:13:22.837+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:13:22.837+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:13:22.843+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:13:22.842+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:13:22.845+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:13:22.865+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.035 seconds
[2023-06-14T01:13:53.540+0000] {processor.py:157} INFO - Started process (PID=8962) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:13:53.542+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:13:53.545+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:13:53.545+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:13:53.552+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:13:53.550+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:13:53.553+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:13:53.573+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.036 seconds
[2023-06-14T01:14:24.172+0000] {processor.py:157} INFO - Started process (PID=9019) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:14:24.175+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:14:24.178+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:14:24.177+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:14:24.184+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:14:24.182+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:14:24.184+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:14:24.206+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.037 seconds
[2023-06-14T01:14:54.784+0000] {processor.py:157} INFO - Started process (PID=9076) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:14:54.785+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:14:54.788+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:14:54.788+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:14:54.794+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:14:54.792+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:14:54.794+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:14:54.813+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.032 seconds
[2023-06-14T01:15:25.353+0000] {processor.py:157} INFO - Started process (PID=9133) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:15:25.355+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:15:25.357+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:15:25.357+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:15:25.363+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:15:25.361+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:15:25.363+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:15:25.381+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.032 seconds
[2023-06-14T01:15:55.483+0000] {processor.py:157} INFO - Started process (PID=9189) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:15:55.486+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:15:55.489+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:15:55.489+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:15:55.497+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:15:55.494+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:15:55.498+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:15:55.523+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.043 seconds
[2023-06-14T01:16:25.612+0000] {processor.py:157} INFO - Started process (PID=9246) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:16:25.614+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:16:25.617+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:16:25.617+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:16:25.624+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:16:25.622+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:16:25.625+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:16:25.650+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.041 seconds
[2023-06-14T01:16:55.946+0000] {processor.py:157} INFO - Started process (PID=9304) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:16:55.949+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:16:55.951+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:16:55.951+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:16:55.958+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:16:55.956+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:16:55.959+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:16:55.983+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.040 seconds
[2023-06-14T01:17:26.151+0000] {processor.py:157} INFO - Started process (PID=9361) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:17:26.153+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:17:26.155+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:17:26.155+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:17:26.161+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:17:26.159+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:17:26.162+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:17:26.180+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.032 seconds
[2023-06-14T01:17:56.415+0000] {processor.py:157} INFO - Started process (PID=9417) to work on /opt/airflow/dags/gcp_test.py
[2023-06-14T01:17:56.417+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/gcp_test.py for tasks to queue
[2023-06-14T01:17:56.419+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:17:56.419+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:17:56.424+0000] {logging_mixin.py:149} INFO - [2023-06-14T01:17:56.423+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/gcp_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcp_test.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.gcs import GoogleCloudStorageListOperator
ImportError: cannot import name 'GoogleCloudStorageListOperator' from 'airflow.providers.google.cloud.operators.gcs' (/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py)
[2023-06-14T01:17:56.425+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/gcp_test.py
[2023-06-14T01:17:56.444+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gcp_test.py took 0.032 seconds
