[2023-06-15T16:04:56.998+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs-files-dag.execute_query_save manual__2023-06-15T16:04:55.086428+00:00 [queued]>
[2023-06-15T16:04:57.004+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs-files-dag.execute_query_save manual__2023-06-15T16:04:55.086428+00:00 [queued]>
[2023-06-15T16:04:57.005+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-15T16:04:57.013+0000] {taskinstance.py:1327} INFO - Executing <Task(BigQueryInsertJobOperator): execute_query_save> on 2023-06-15 16:04:55.086428+00:00
[2023-06-15T16:04:57.019+0000] {standard_task_runner.py:57} INFO - Started process 2059 to run task
[2023-06-15T16:04:57.023+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gcs-files-dag', 'execute_query_save', 'manual__2023-06-15T16:04:55.086428+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/gcp_test.py', '--cfg-path', '/tmp/tmpedodjocg']
[2023-06-15T16:04:57.024+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask execute_query_save
[2023-06-15T16:04:57.071+0000] {task_command.py:410} INFO - Running <TaskInstance: gcs-files-dag.execute_query_save manual__2023-06-15T16:04:55.086428+00:00 [running]> on host 6f3c5cb11aa3
[2023-06-15T16:04:57.140+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs-files-dag' AIRFLOW_CTX_TASK_ID='execute_query_save' AIRFLOW_CTX_EXECUTION_DATE='2023-06-15T16:04:55.086428+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-15T16:04:55.086428+00:00'
[2023-06-15T16:04:57.151+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-06-15T16:04:57.152+0000] {bigquery.py:2608} INFO - Executing: {'query': {'query': "\n                CREATE OR REPLACE EXTERNAL TABLE `bus-data-389717.external_data`\n                    OPTIONS (\n                        format = 'PARQUET',\n                        uris = ['gs://data_lake_bus_data_bus-data-389717/year=2023/month=06/day=14/hour=19/part_3ec267d7-48f5-4e1f-a19a-57889111a3e3_19:46:00.parquet']\n                    );\n                ", 'useLegacySql': False, 'writeDisposition': 'WRITE_EMPTY', 'destinationTable': {'projectId': 'bus-data-389717', 'datasetId': 'dbt_busdata_stag', 'tableId': 'external_data'}}}'
[2023-06-15T16:04:57.201+0000] {bigquery.py:1562} INFO - Inserting job ***_gcs_files_dag_execute_query_save_2023_06_15T16_04_55_086428_00_00_2ab93711de0815b93b50823a37c573d1
[2023-06-15T16:04:58.142+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2659, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1499, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1489, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Cannot set destination table in jobs with DDL statements

Location: southamerica-east1
Job ID: airflow_gcs_files_dag_execute_query_save_2023_06_15T16_04_55_086428_00_00_2ab93711de0815b93b50823a37c573d1

[2023-06-15T16:04:58.154+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=gcs-files-dag, task_id=execute_query_save, execution_date=20230615T160455, start_date=20230615T160456, end_date=20230615T160458
[2023-06-15T16:04:58.164+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 30 for task execute_query_save (400 Cannot set destination table in jobs with DDL statements

Location: southamerica-east1
Job ID: airflow_gcs_files_dag_execute_query_save_2023_06_15T16_04_55_086428_00_00_2ab93711de0815b93b50823a37c573d1
; 2059)
[2023-06-15T16:04:58.196+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-15T16:04:58.212+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
