[2023-06-22T17:31:02.894+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: running-buses-dbt-dag.dbt_run manual__2023-06-22T17:30:05.310605+00:00 [queued]>
[2023-06-22T17:31:02.900+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: running-buses-dbt-dag.dbt_run manual__2023-06-22T17:30:05.310605+00:00 [queued]>
[2023-06-22T17:31:02.900+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-22T17:31:02.907+0000] {taskinstance.py:1327} INFO - Executing <Task(DbtRunOperator): dbt_run> on 2023-06-22 17:30:05.310605+00:00
[2023-06-22T17:31:02.912+0000] {standard_task_runner.py:57} INFO - Started process 1403 to run task
[2023-06-22T17:31:02.917+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'running-buses-dbt-dag', 'dbt_run', 'manual__2023-06-22T17:30:05.310605+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/running_buses_dbt_dag.py', '--cfg-path', '/tmp/tmpnvozecma']
[2023-06-22T17:31:02.922+0000] {standard_task_runner.py:85} INFO - Job 139: Subtask dbt_run
[2023-06-22T17:31:02.972+0000] {task_command.py:410} INFO - Running <TaskInstance: running-buses-dbt-dag.dbt_run manual__2023-06-22T17:30:05.310605+00:00 [running]> on host 6bba1fead03c
[2023-06-22T17:31:03.027+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='running-buses-dbt-dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2023-06-22T17:30:05.310605+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-22T17:30:05.310605+00:00'
[2023-06-22T17:31:03.030+0000] {dbt_hook.py:117} INFO - dbt run --profiles-dir /opt/***/tmp_data/dbt_bus_data/.dbt_profile --target stg_running_buses.sql
[2023-06-22T17:31:03.033+0000] {dbt_hook.py:126} INFO - Output:
[2023-06-22T17:31:05.725+0000] {dbt_hook.py:130} INFO - [0m17:31:05  Running with dbt=1.5.1
[2023-06-22T17:31:05.752+0000] {dbt_hook.py:130} INFO - [0m17:31:05  Encountered an error:
[2023-06-22T17:31:05.753+0000] {dbt_hook.py:130} INFO - Runtime Error
[2023-06-22T17:31:05.756+0000] {dbt_hook.py:130} INFO -   The profile 'dbt_bus_data' does not have a target named 'stg_running_buses.sql'. The valid target names for this profile are:
[2023-06-22T17:31:05.758+0000] {dbt_hook.py:130} INFO -    - dev
[2023-06-22T17:31:06.557+0000] {dbt_hook.py:132} INFO - Command exited with return code 2
[2023-06-22T17:31:06.569+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow_dbt/operators/dbt_operator.py", line 98, in execute
    self.create_hook().run_cli('run')
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow_dbt/hooks/dbt_hook.py", line 138, in run_cli
    raise AirflowException("dbt command failed")
airflow.exceptions.AirflowException: dbt command failed
[2023-06-22T17:31:06.573+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=running-buses-dbt-dag, task_id=dbt_run, execution_date=20230622T173005, start_date=20230622T173102, end_date=20230622T173106
[2023-06-22T17:31:06.592+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 139 for task dbt_run (dbt command failed; 1403)
[2023-06-22T17:31:06.622+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-22T17:31:06.642+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
